"""add is_required to Attribut

Revision ID: 30b4282c1de3
Revises: 26952e9334ac
Create Date: 2023-10-12 22:25:30.145819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b4282c1de3'
down_revision: Union[str, None] = '26952e9334ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributs', sa.Column('is_required', sa.Boolean(), nullable=True, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attributs', 'is_required')
    # ### end Alembic commands ###
